#!/usr/bin/env bash

set -eou pipefail

. oks-lib.sh

command_on_path lpinfo
command_on_path systemctl
command_on_path sed
command_on_path oks

# NixOS generates `printers.conf` for us but we can't know the printers SN in
# advance of the first ceremony where it's used. As a work-around we query cups
# for the serial number for the attached printer and then swap it in
# `printers.conf` with the place holder `SN_GOES_HERE`
PRINTER_SN_REGEX='^direct[[:space:]]\+usb:\/\/Brother\/QL-600?serial=\(.*\)$'
PRINTER_SN=$(lpinfo -v | sed -n "s/$PRINTER_SN_REGEX/\1/p")
info "Label printer with SN: $PRINTER_SN found"

systemctl stop cups.service
sed -i "s/SN_GOES_HERE/$PRINTER_SN/g" /etc/cups/printers.conf
systemctl start cups.service
info "Label printer with SN: $PRINTER_SN configured"

while read -rsp "Enter password: " OKS_PASSWORD; do
    export OKS_PASSWORD

    if ! oks hsm --auth-id 2 serial-number --auth-method stdio > /dev/null 2>&1; then
        echo "incorrect password, please try again ..."
    else
        echo -e "success!"

        read -rsp "Press the \"Enter\" key to begin the ceremony:"
        echo ""
        break
    fi
done

# challenge operator for YubiHSM password over stdio change the auth
# value to a new randomly generated one export the new password to CDW
info "Changing OKS auth value: auth from STDIO, output to CDW"
oks hsm change-auth --auth-method stdio --secret-method cdw

unset OKS_PASSWORD

# sign the input requests from /usr/share/oks using the CD for
# authentication
info "Signing requests: auth from CDW"
oks ca --auth-method cdr sign
