#!/usr/bin/env bash

set -eou pipefail

. oks-lib.sh

# challenge operator for YubiHSM password over stdio change the auth
# value to a new randomly generated one export the new password to CDW
info "Changing OKS auth value: auth from STDIO, output to CDW"
oks hsm change-auth --auth-method stdio --secret-method cdw

# sign the input requests from /usr/share/oks using the CD for
# authentication
info "Signing requests: auth from CDW"
oks ca --auth-method cdr sign
