#!/usr/bin/env bash

set -eou pipefail

. oks-lib.sh

command_on_path blockdev
command_on_path lpinfo
command_on_path systemctl
command_on_path sed
command_on_path oks

eject "$CD_DEV"
echo -e "\nInsert OKS HSM Auth CD, close drive tray,"
read -p "then press Enter to continue..."
COUNT=5
while [ $COUNT -gt 0 ]; do
    if ! blockdev --getsize64 "$CD_DEV" >/dev/null 2>&1; then
        COUNT=$(($COUNT-1))
        echo "Waiting for CD drive to \"settle\""
        sleep 10
    else
        break
    fi
done

info "Storage usage before ceremony: "
oks hsm storage-info --auth-method cdr

info "Generating keys from keyspecs ..."
oks hsm generate --auth-method cdr

info "Initializing CAs for keyspecs ..."
oks ca --auth-method cdr initialize

info "Signing requests intermediates & debug auth credentials"
oks ca --auth-method cdr sign

info "Storage usage after ceremony: "
oks hsm storage-info --auth-method cdr
