#!/usr/bin/env bash

set -eou pipefail

. oks-lib.sh

CEREMONY_SCRIPT=_ceremony

if [ ! -e "$OUTPUT" ]; then
    info "Creating output directory."
    mkdir -p "$OUTPUT"
fi

if ! blockdev --getsize64 "$CD_DEV" > /dev/null 2>&1; then
    echo -ne "\nExpected CD in \"$CD_DEV\", please insert one, close the tray,\nthen press any key to continue:"
    eject "$CD_DEV"
    wait_for_key_press
    echo -ne "\n"
fi

info "Starting terminal session recording."
script \
    --timing="$OUTPUT"/script-timing.log \
    --command "hash-cd --no-print && $CEREMONY_SCRIPT" \
    "$OUTPUT"/script.log

info "Script session ended"

eject "$CD_DEV"
echo -ne "\nInsert blank media into CD drive then press any key to burn output disk:"
wait_for_key_press
echo -ne "\n"

# export all data from /var/lib/oks to CDW
wait_for_cd
write-output

echo -e "\nOutput written to CDW. The ceremony is now complete."
echo -n "Press the Enter key to poweroff:"
wait_for_key_press

poweroff
