#!/usr/bin/env bash

set -euo pipefail

. oks-lib.sh

while true; do
    echo -n "Enter new HSM password: "
    read -s PASSWD0
    echo
    read -s -p "Enter password again to confirm: " PASSWD1
    echo
    if [ "$PASSWD0" == "$PASSWD1" ]; then
        break
    else
        echo "Passwords entered do not match. Try again."
    fi
done

info "Initializing HSM"
OKS_NEW_PASSWORD="$PASSWD0" oks hsm initialize

info "Generating keys"
OKS_PASSWORD="$PASSWD0" oks hsm generate

info "Initializing CAs"
OKS_PASSWORD="$PASSWD0" oks ca initialize

info "Signing CSRs"
OKS_PASSWORD="$PASSWD0" oks ca sign
