#!/usr/bin/env bash

set -euo pipefail

# This script calculates the hash of the ISO FS on a CD or DVD.

. oks-lib.sh

TMP_DIR=$(mktemp --directory)
trap 'rm -rf -- "$TMP_DIR"' EXIT

info "calculating hash of CD in \"$CD_DEV\""
HASH=$(cd_sha256 "$CD_DEV" "$TMP_DIR")
info "CD in \"$CD_DEV\" has hash \"sha256-$HASH\""
