#!/usr/bin/env bash

set -euo pipefail

# This script calculates the hash of the ISO FS on a CD or DVD.

. oks-lib.sh

TMP_DIR=$(mktemp --directory)
trap 'rm -rf -- "$TMP_DIR"' EXIT

info "calculating digest of CD in \"$CD_DEV\""
HASH=$(
    cd_sha256 "$CD_DEV" "$TMP_DIR" \
        | awk '{gsub(/.{2}/,"& ")}1' \
        | sed 's/ /\n/8;P;D' \
        | head -c -1
)
info "CD in \"$CD_DEV\" has sha256 digest:\n$HASH"

if lpstat -p ql-600 > /dev/null; then
    lp -o PageSize=62x29mm <<< "$HASH" > /dev/null
else
    info "no printer found, the digest must be transcribed manually"
fi
