#!/usr/bin/env bash

set -euo pipefail

# This script calculates the hash of the ISO FS on a CD or DVD.

. oks-lib.sh

print_usage ()
{
    cat <<END
USAGE:
    "${0##*/}" <CDROM>

<CDROM> - path to CDROM device (default: $CD_DEV)
END
}

while test $# -gt 0; do
    case $1 in
        -h|--help) print_usage; exit $?;;
        --) shift; break;;
        -*) usage_error "invalid option: '$1'";;
        *) break;
    esac
    shift
done

if [ $# -eq 1 ]; then
    CD_DEV="$1"
fi

if [ $# -gt 1 ]; then
    >&2 echo "unepected positional parameters"
    exit 1
fi

TMP_DIR=$(mktemp --directory)
trap 'rm -rf -- "$TMP_DIR"' EXIT

info "calculating digest of CD in \"$CD_DEV\""
HASH=$(
    cd_sha256 "$CD_DEV" "$TMP_DIR" \
        | awk '{gsub(/.{2}/,"& ")}1' \
        | sed 's/ /\n/8;P;D' \
        | head -c -1
)
info "CD in \"$CD_DEV\" has sha256 digest:\n$HASH"
