#!/usr/bin/env bash

set -eou pipefail

. oks-lib.sh

info "Creating output directory."
mkdir -p "$OUTPUT"

info "Starting terminal session recording."
script --t="$OUTPUT"/script-timing.log -a "$OUTPUT"/script.log
