#!/usr/bin/env bash

set -euo pipefail

# This script expects a directory name / path as a single positional
# parameter. The contents of this directory are turned into an ISO and
# then burned to a CD / DVD.

. oks-lib.sh

# commands / executables that we need
command_on_path mkisofs
command_on_path cdrecord

TMP_DIR=$(mktemp --directory)
trap 'rm -rf -- "$TMP_DIR"' EXIT

ISO=$TMP_DIR/temp.iso

# generate iso from directory
info "generating iso from directory \"$OUTPUT\""
fail_with_stderr mkisofs -r -iso-level 4 -o "$ISO" "$OUTPUT" > /dev/null

if [ ! -f "$ISO" ]; then
    error "ISO successfully created but \"$ISO\" is not a file"
fi

# get hash of iso
ISO_HASH=$(
    sha256sum "$ISO" | awk '{print $1}' \
        | awk '{gsub(/.{2}/,"& ")}1' \
        | sed 's/ /\n/8;P;D' \
        | head -c -1
)
info "ISO has sha256 digest:\n$ISO_HASH"

# cdrecord is noisy on both stdio and stderr. We can't redirect stderr while
# using 'fail_with_msg' so we do it manually.
info "writing ISO to device: \"$CD_DEV\""

fail_with_stderr \
    cdrecord -eject -data "$ISO" dev="$CD_DEV" gracetime=0 timeout=1000 speed=1 \
    > /dev/null
