name: license-check
on: pull_request
permissions:
  contents: read

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        toolchain: 1.88
    - name: Check License Header
      uses: apache/skywalking-eyes/header@454b8ead48f7073cd40ea20487fdfb2409247e69
