name: license-check
on: pull_request
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        toolchain: 1.64.0
    - name: Check License Header
      uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff
