name: license-check
on: pull_request
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        toolchain: 1.69.0
    - name: Check License Header
      uses: apache/skywalking-eyes/header@e6d1ce46901c759d9d9f84f8bcb97ad028cd5f88
