name: license-check
on: pull_request
jobs:
  license:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        toolchain: 1.79
    - name: Check License Header
      uses: apache/skywalking-eyes/header@15169715c708117b82c08116399ac1776bdf833e
