name: linters
on: [push, pull_request]
permissions:
  contents: read

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy
          toolchain: 1.88
      - run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libudev-dev
      - run: cargo clippy -- --deny warnings
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: warning
